### PR TITLE
feat/enforce-code-styles

### PR DESCRIPTION
**Pull request by ZuperZee**
Add more strongly opinionated code and checks.

### CODE REVIEW

**Review by flesa — APPROVED** [review]

**Review by sbgap — APPROVED** [review]
Looks good

**Comment by ZuperZee** [comment]
> Looks good

To who?

**Comment by sbgap** [comment]
> > Looks good
> 
> To who?

To you i guess

**Review by sbgap — APPROVED** [review]
ZuperZee thinks it looks good

**Review by flesa — APPROVED** [review]
LGTY

**Pull request merged**
